version: "3.8"
services:
  php-apache-environment:
    container_name: Student_db
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db_student
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: student_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test1234
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3000:80"
    restart: always
    environment:
      PMA_HOST: db_student
    depends_on:
      - db